[package]
name = "copycat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize = "0.4.1"
clipboard = "0.5.0"
dirs = "4.0.0"
